name: Origins-Fantasy-Enhanced
version: ${version}
main: com.starshootercity.originsfantasy.OriginsFantasy
description: Origins-Reborn addon adding fantasy themed origins
api-version: '1.19'
author: cometcake575
depend:
  - Origins-Reborn-Enhanced
  - EnderaLib